= Diversity, inclusion & belonging

Diversity is the facts you bring with your person, it's something you cannot change when you walk in through the door.

Inclusion is the act of creating fairness. It is about cultivating, and it is the job of everyone. Things that make people feel included:

* They're expected to be there, and they're expected to be good.
* They're reflected in the policies and the practices, formal and informal
* They feel like they are engaged in the most exciting aspects of that particular environment, that they're not left out.

Belonging is a human need to belong in our unique way. Questions to ask to determine if you feel like you belong:

* When something bad happens, I know someone cares about me.
* I have friends at work.

Micro-inequities are micro-aggressions.

== SPACE2 model of mindful inclusion

* *Slowing down:* Being mindful and considered in your responses to others.
* *Perspective taking:* Actively imaginging the thoughts and feelings of others.
* *Asking yourself:* Active self-questioning to challenge your assumptions.
* *Cultural intelligence:* Interpreting a person's behaviour through their cultural lens rather than your own.
* *Exemplars:* Identifying counter-stereotypical individuals.
* *Expand:* The formation of diverse friendships.

Source: https://cultureplusconsulting.com/2018/10/17/six-proven-strategies-for-managing-unconscious-bias/[The SPACE2 Model of Mindful Inclusion: Six Proven Strategies for Managing Unconscious Bias]

== Winters Group 4E model

* Exposure
* Experience
* Education
* Empathy

== Six components of an apology:

. Acknowledge responsibility
. Offer to repair the issue
. Express regret
. Explain what went wrong
. Repent for the problem
. Request forgiveness

== Other notes

Know when to pause when emotions are high. No effective shared understanding can happen in these circumstances.

* Acts
* Learns
* Listens
* Yields

