= Favourite Quotes
:toc:

== How to live

[verse, 'https://en.wikipedia.org/wiki/Seikilos_epitaph[Seikilos epitaph]']
While you live, shine
have no grief at all
life only exists for a short while
and time demands an end.

[verse, Harry Chapin, I Wonder What Would Happen To This World]
Oh if a man tried
To take his time on Earth
And prove before he died
What one man's life could be worth
Well I wonder what would happen
to this world

[verse, Hardwell (feat. Matthew Koma), Dare You]
Let your heart be your religion
Let it break you out of this prison you became
It's not too late.

[verse, Dave Matthews Band, The Space Between]
The space between
what's wrong and right
is where you'll find me hiding, waiting for you.

[quote, 'Alan Watts, British philosopher']
Better to have a short life that is full of what you like doing, than a long life that is spent in a miserable way.

[quote, Solid Snake, 'https://youtu.be/I5AunfmI8bs?t=18280[Metal Gear Solid 2: Sons of Liberty]']
We can tell other people about having faith. What we had had faith in. What we found important enough to fight for. *It's not whether you were right or wrong, but how much faith you were willing to have: that decides the future.*

[quote, Kamina, Tenga Toppa Gurren Lagann]
Don't be distracted by the what-ifs, should-haves, and if-onlys. The one path you choose yourself — that is the truth of your universe.

[quote, Naruto Uzumaki, Naruto: Shippuden (Ch. 647)]
I refuse to leave behind any regrets… I don't wanna look back and think, 'what might have been'!!!

[quote, Amelia Croft, Rise of the Tomb Raider]
You become who you are through your choices, through the love you give and the promises you keep.

[quote, Unknown]
Only fools let compliments get to their heads and criticism get to their heart.

[quote, Graham Crossford, Octopath Traveler]
For life is a journey. The places you go… The deeds you do… The tales whose hero you become… Every road is yours to take. So journey forth, friend, into this great world we live in… and find an adventure all your own.

== How to create

[quote, Linds Redding, 'https://web.archive.org/web/20160816090956/http://www.lindsredding.com/2012/03/11/a-overdue-lesson-in-perspective/[A Short Lesson in Perspective]']
To start the day with nothing, and to end it with something that didn't exist yesterday is a wondrous and magical thing. It never gets old. Making shit. That's where the fun is. And the wonder. And the glory.

[quote, Bob Ross, 'The Joy of Painting, https://www.youtube.com/watch?v=GARWowi0QXI&t=783s[Meadow Lake, Season 2, Episode 1]']
Talent is a pursued interest. In other words, anything that you're willing to practise, you can can do.

== How to understand

[quote, Søren Kierkegaard]
Life can only be understood backwards; but it must be lived forwards.

[quote, Robert Frobisher, Cloud Atlas (movie)]
All boundaries are conventions, waiting to be transcended. One may transcend any convention, if only one can first conceive of doing so.

[quote, Conrad Roth, Tomb Raider (2013)]
Sacrifice is a choice you make; loss is a choice made for you.

[quote, Cattleya Baudelaire, 'Violet Evergarden, Episode 2']
Words can have different interpretations. What one says isn't the whole truth. It's a human weakness. They test others to confirm their own existence. It's a contradiction

[verse, 'JJ Lin (林俊杰)', '不为谁而作的歌 (Twilight)']
____
梦为努力浇了水
爱在背后往前推
当我抬起头才发觉
我是不是忘了谁

累到整月不能睡
夜色哪里都是美
一定有个人  他
躲过 避过 闪过 瞒过
他是谁
____

== How to teach

[quote, Robin Wall Kimmerer, 'Braiding Sweetgrass: Indigenous Wisdom, Scientic Knowledge and the Teaching of Plants']
This is our work, to discover what we can give. Isn't this the purpose of education, to learn the nature of your own gifts and how to use them for good in the world?

[quote, Yoda, Star Wars: The Last Jedi]
Heeded my words not, did you? Pass on what you have learned. Strength, mastery. But weakness, folly, failure also. Yes, failure most of all. *The greatest teacher, failure is. Luke, we are what they grow beyond. That is the true burden of all masters.*

[quote, Anton Ego, Ratatouille]
In many ways, the work of a critic is easy. We risk very little, yet enjoy a position over those who offer up their work and their selves to our judgement. We thrive on negative criticism, which is fun to write and to read. But the bitter truth we critics must face is that, in the grand scheme of things, the average piece of junk is probably more meaningful than our criticism designating it so. But there are times when a critic truly risks something, and that is in the discovery and defense of the new. The world is often unkind to new talent, new creations. The new needs friends.

== How to parent

[verse, 'https://www.youtube.com/watch?v=cJW5n8f0Z9o[Della\'s Moon Lullaby]', DuckTales]
Look to the stars my darling baby boys
Life is strange and vast
Filled with wonders and joys.
Face each new sun with eyes clear and true
Unafraid of the unknown
Because I'll face it all with you.

[quote, Catherine M. Wallace]
Listen earnestly to anything [your children] want to tell you, no matter what. If you don't listen eagerly to the little stuff when they are little, they won't tell you the big stuff when they are big, because to them all of it has always been big stuff.

[quote, Kobe Bryant, 'https://www.theplayerstribune.com/en-us/articles/kobe-bryant-letter-to-my-younger-self[Letter to My Younger Self]']
You will come to understand that you were taking care of them because it made YOU feel good, it made YOU happy to see them smiling and without a care in the world — and that was extremely selfish of you. While you were feeling satisfied with yourself, you were slowly eating away at their own dreams and ambitions. You were adding material things to their lives, but subtracting the most precious gifts of all: independence and growth.

== How to do things

[quote, Maya Angelou]
I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.

[quote, 'Martin Luther King, Jr.']
The ultimate weakness of violence is that it is a descending spiral, begetting the very thing it seeks to destroy. Instead of diminishing evil, it multiplies it. Through violence you may murder the liar, but you cannot murder the lie, nor establish the truth. Through violence you murder the hater, but you do not murder hate. In fact, violence merely increases hate… Returning violence for violence multiplies violence, adding deeper darkness to a night already devoid of stars. *Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.*

[quote, Robert G. Ingersoll, 'https://archive.org/details/abrahamlincolnle00inge/page/52/mode/2up[Abraham Lincoln, A Lecture (1895)]']
Nothing discloses real character like the use of power. It is easy for the weak to be gentle. Most people can bear adversity. But if you wish to know what a man really is, give him power. This is the supreme test. It is the glory of Lincoln that, having almost absolute power, he never abused it, except on the side of mercy.

[quote, Stilgar, 'Dune, Frank Herbert']
A leader, you see, is one of the things that distinguishes a mob from a people. He maintains the level of individuals. Too few individuals, and a people reverts to a mob.

[quote, Elon Musk, 'https://arstechnica.com/science/2020/03/inside-elon-musks-plan-to-build-one-starship-a-week-and-settle-mars/[_Inside Elon Musk’s plan to build one Starship a week—and settle Mars_], Ars Technica']
If you email me directly, and if I buy off on the risk, then it’s OK. What’s not OK is they think that the weld is not good, they don’t tell me, they take it to the pad and blow it up. Now I have been clear. There’s plenty of forgiveness if you pass me the buck. There is no forgiveness if you don’t.

== How to feel

[quote, Proverbs 4:23 (NIV)]
Above all else, guard your heart, for everything you do flows from it.

[quote, Harry Chapin, Sequel]
We talked 'cause talking tells you things like what you really are thinking about / but *sometimes you can't find what you're feeling 'til all the words run out.*

[quote, René Leriche, 'La philosophie de la chirurgie, 1951']
Every surgeon carries within himself a small cemetery, where from time to time he goes to pray — a place of bitterness and regret, where he must look for an explanation for his failures.

[quote, Iroh, Avatar the Last Airbender]
Pride is not the opposite of shame, but its source. True humility is the only antidote to shame.

== How to die

[verse, Nick Drake, Cello Song]
So forget this cruel world
where I belong
I'll just sit and wait
and sing my song.

[quote, 'Poor Jerusalem, Jesus Christ Superstar']
To conquer death you only have to die. You only have to die.

[quote, Itachi Uchiha, Naruto: Shippuden (Ch. 508)]
We don't know what kind of people we truly are until the moment before our deaths. As death comes to embrace you, you will realise what you are. That is what death is, don't you think?

[quote, Roy Batty, Blade Runner]
I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhäuser Gate. *All those moments will be lost in time, like tears in rain.* Time to die.
